# Generated by Django 2.2.1 on 2019-07-12 15:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('fecha', models.DateField(verbose_name='fecha de publicación')),
                ('resumen', models.TextField()),
                ('calificacion', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('estatus', models.CharField(choices=[('Finalizado', 'Finalizado'), ('En ejecución', 'En ejecución')], max_length=15)),
                ('escuela', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PalabraClave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra', models.CharField(max_length=120)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisrmm.Tesis')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('tutor', models.BooleanField(default=False)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisrmm.Tesis')),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(max_length=120)),
                ('correo', models.CharField(max_length=120)),
                ('escuela', models.CharField(max_length=120)),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tesisrmm.Tesis')),
            ],
        ),
    ]
