# Generated by Django 2.2.1 on 2019-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tesis',
            name='estatus',
            field=models.CharField(choices=[('Finalizado', 'Finalizado'), ('En ejecución', 'En ejecución')], max_length=10),
        ),
    ]
