# Generated by Django 2.2.1 on 2019-07-12 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Tesis', 'nombre', 'tes_nombre'),
        migrations.RenameField('Tesis', 'fecha', 'tes_fecha'),
        migrations.RenameField('Tesis', 'resumen', 'tes_resumen'),
        migrations.RenameField('Tesis', 'estatus', 'tes_estatus'),
        migrations.RenameField('Tesis', 'calificacion', 'tes_calificacion'),
        migrations.RenameField('Tesis', 'escuela', 'tes_escuela'),
    ]
