# Generated by Django 2.2.1 on 2019-07-12 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0002_auto_20190712_1237'),
    ]

    operations = [
        migrations.RenameField('Tesis', 'tes_nombre', 'nombre'),
        migrations.RenameField('Tesis', 'tes_fecha', 'fecha'),
        migrations.RenameField('Tesis', 'tes_resumen', 'resumen'),
        migrations.RenameField('Tesis', 'tes_estatus', 'estatus'),
        migrations.RenameField('Tesis', 'tes_calificacion', 'calificacion'),
        migrations.RenameField('Tesis', 'tes_escuela', 'escuela'),
    ]
