# Generated by Django 2.2.1 on 2019-07-14 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0003_auto_20190712_1244'),
    ]

    operations = [
        migrations.RenameField('Autor', 'nombre', 'aut_nombre'),
        migrations.RenameField('Autor', 'apellido', 'aut_apellido'),
        migrations.RenameField('Autor', 'correo', 'aut_correo'),
        migrations.RenameField('Autor', 'escuela', 'aut_escuela'),
    ]
