# Generated by Django 2.2.1 on 2019-07-14 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0004_auto_20190714_1039'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='tesis',
            new_name='aut_tesis',
        ),
    ]
