# Generated by Django 2.2.1 on 2019-07-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0005_auto_20190714_1040'),
    ]

    operations = [
        migrations.RenameField('Evaluador', 'nombre', 'eva_nombre'),
        migrations.RenameField('Evaluador', 'apellido', 'eva_apellido'),
        migrations.RenameField('Evaluador', 'tutor', 'eva_tutor'),
    ]
