# Generated by Django 2.2.1 on 2019-07-14 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0006_auto_20190714_1055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluador',
            old_name='tesis',
            new_name='eva_tesis',
        ),
    ]
