# Generated by Django 2.2.1 on 2019-07-14 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0008_auto_20190714_1124'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
    ]
