# Generated by Django 2.2.1 on 2019-07-14 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tesisrmm', '0009_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SignUp',
        ),
    ]
